Repository Incruises/InGroup, pull requests merged in 2024-03, with the labels that each got.

#3 fix(in-group/index) fixed scaling INC-6615
  index.html
Labels: Ready to merge!

#4 fix(index): remove book url (INC-6781)
  index.html
Labels: Test pending!

#5 update(): Add new inGroup Logos (INC-6866)
  es.html
  files/brands/_inGroup_Original.svg
  files/brands/_inGroup_allWhite.svg
  files/brands/_inGroup_black.svg
  files/brands/_inGroup_grey.svg
  files/brands/_ingroup_WhiteText.svg
  index.html
Labels: Code Review Pending
